services:
  scheduler:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    environment:
      FUNCTION: "scheduler"
    restart: unless-stopped
    networks:
      - app_network
    volumes:
      - "logs_v:/app/storage/logs:rw"

    healthcheck:
      disable: true
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy

  webserver:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    environment:
      FUNCTION: "webserver"
      WEB_THREADS: 2
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
    networks:
      - app_network
    volumes_from:
      - scheduler
    depends_on:
      - scheduler

  reverb:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    environment:
      FUNCTION: "reverb"
      REVERB_PORT: "${REVERB_PORT:-8080}"
    restart: unless-stopped
    ports:
      - "${REVERB_PORT:-8080}:${REVERB_PORT:-8080}"
    networks:
      - app_network
    volumes_from:
      - scheduler
    healthcheck:
      disable: true

  pulse:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    environment:
      FUNCTION: "pulse"
    restart: unless-stopped
    networks:
      - app_network
    volumes_from:
      - scheduler
    depends_on:
      scheduler:
        condition: service_healthy
    healthcheck:
      disable: true

  worker:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    privileged: true
    restart: unless-stopped
    environment:
      FUNCTION: "worker"
    networks:
      - app_network
    volumes_from:
      - scheduler
    depends_on:
      - scheduler
    healthcheck:
      disable: true

  mysql:
    image: "mysql/mysql-server:8.0"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "db_v:/var/lib/mysql"
    networks:
      - app_network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-p${DB_PASSWORD}"
      retries: 3
      timeout: 5s
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    tmpfs:
      - /data
    networks:
      - app_network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    command: 'redis-server --save "" --appendonly no'

  minio:
    image: "minio/minio:latest"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: sail
      MINIO_ROOT_PASSWORD: password
    volumes:
      - "minio_v:/data/minio"
    networks:
      - app_network
    entrypoint: sh
    command: -c 'mkdir -p /data/minio/${AWS_BUCKET} && minio server /data/minio --console-address ":8900"'
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://localhost:9000/minio/health/live"
      retries: 3
      timeout: 5s

networks:
  app_network:
    driver: bridge
volumes:
  logs_v:
    driver: local
  db_v:
    driver: local
  minio_v:
    driver: local
