#!/bin/bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer


git config --global --add safe.directory /var/www/html
cd /var/www/html
composer install

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
