#!/bin/bash

echo '!Starting container!'

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

echo '!Copping vendor!'
git config --global --add safe.directory /var/www/html
cd /var/www/html
composer install || cp /var/www/vendor/* /var/www/html/vendor -R

echo '!Migrating!'

php artisan migrate

echo '!Storage Link!'

php artisan storage:link

echo '!Starting container!'


if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
