FROM wyveo/nginx-php-fpm:php82

ENV WWWGROUP=nginx
WORKDIR /usr/share/nginx/html

RUN apt update
RUN apt install -y ca-certificates curl gnupg dos2unix

RUN curl -sLS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
ENV NODE_MAJOR=20
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

COPY . /usr/share/nginx/html
RUN chown -Rf nginx:nginx /usr/share/nginx/html

RUN apt-get update && apt-get install nodejs -y

RUN curl -qL https://www.npmjs.com/install.sh | sh

RUN composer install --no-interaction --optimize-autoloader --no-scripts

RUN npm install
RUN npm build
RUN rm -rf node_modules

RUN git config --global --add safe.directory /var/www/html


COPY ./docker/prod/start.sh /start.sh
COPY ./docker/prod/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Set permissions in folders
RUN dos2unix /etc/supervisor/conf.d/supervisord.conf
RUN dos2unix /start.sh
RUN chmod +x /start.sh

RUN apt-get purge -y nodejs npm ca-certificates curl gnupg dos2unix &&\
    rm -r /etc/apt/sources.list.d/nodesource.list &&\
    rm -r /etc/apt/keyrings/nodesource.gpg

RUN apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
