FROM wyveo/nginx-php-fpm:php82

ENV WWWGROUP=nginx
WORKDIR /usr/share/nginx/html

RUN apt update
RUN apt install -y ca-certificates curl gnupg

RUN curl -sLS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
ENV NODE_MAJOR=20
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

COPY . /usr/share/nginx/html
RUN chmod -Rf nginx:nginx /usr/share/nginx/html

RUN composer install --no-interaction --optimize-autoloader --no-scripts

RUN git config --global --add safe.directory /var/www/html

RUN apt-get purge -y nodejs &&\
    rm -r /etc/apt/sources.list.d/nodesource.list &&\
    rm -r /etc/apt/keyrings/nodesource.gpg

COPY ./docker/start-container /usr/local/bin/start-container

# Set permissions in folders
RUN dos2unix /usr/local/bin/start-container
RUN chmod +x /usr/local/bin/start-container

ENTRYPOINT [ "start-container" ]
