#! /bin/bash
cd /app

echo "== Starting application =="

# Startup default
printf "\nPULSE_SERVER_NAME=$FUNCTION\n" >> .env


echo "== Configuring cache =="
php artisan cache:clear
php artisan clear-compiled
php artisan config:cache
php artisan event:cache
php artisan route:cache
php artisan view:cache
php artisan optimize 

echo "== Starting my job as $FUNCTION =="
if [ "$FUNCTION" == "scheduler" ]; then
    php artisan migrate --force
    php artisan db:seed --force

    # Start scheduler
    php artisan schedule:work
elif [ "$FUNCTION" == "worker" ]; then
    # Start worker
    # unlimited memory and unlimited execution time
    php -d memory_limit=-1 artisan queue:work --queue=high,contest,submit,rank,low --sleep=2 --tries=2 --backoff=15,30,60 --max-jobs=300 --timeout=0

elif [ "$FUNCTION" == "pulse" ]; then

    # Start pulse worker
    (php artisan pulse:check; [ "$?" -lt 2 ] && kill "$$") &
    (php artisan pulse:work; [ "$?" -lt 2 ] && kill "$$") &
    wait
elif [ "$FUNCTION" == "mailler" ]; then
    # Start mailer
    php artisan queue:work --queue=email --rest=2 --sleep=4 --tries=5 --backoff=10,60,300 --max-time=3600 --timeout=0
elif [ "$FUNCTION" == "reveb" ]; then
    # Start supervisor (reverb+default worker)
    exec supervisord -c /etc/supervisor/conf.d/supervisord.conf
elif [ "$FUNCTION" == "webserver" ]; then
    # Start webserver
    php -d variables_order=EGPCS artisan octane:start --server=frankenphp --host=0.0.0.0 --admin-port=2019 --port=80 --max-requests=10000 --workers=${WEB_THREADS:-4}
fi